stages:
  prepare:
    cmd: python src/prepare.py data/raw_data data/prepared
    deps:
    - data/raw_data
    - src/prepare.py
    outs:
    - data/prepared

  train:
    cmd: python src/train.py data/prepared/train model
    deps:
    - src/train.py
    - data/prepared/train
    outs:
    - model
  
  evaluate:
    cmd: python src/evaluate.py data/prepared/test model
    deps:
    - src/evaluate.py
    - data/prepared/test
    - model
    metrics:
    - evaluation/fragmentation_classification_report.json
    plots:
    - evaluation/fragmentation_confusion_matrix.png