apiVersion: v1
kind: Service
metadata:
  name: pdf-fragmentation-predictor-service
  namespace: pdf-fragmentation-predictor
spec:
  selector:
    app: pdf-fragmentation-predictor
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP